name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug secrets (DO NOT LOG VALUES)
      run: |
        echo " Docker Hub username is set: ${{ secrets.DOCKERHUB_USERNAME }}" 
        echo "Docker Hub token is set: [hidden]"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: georgekagwe/simple-app:latest
